### ISSUE TITLE
Screenshot cannot maintain original aspect ratio

### ISSUE THREAD

**Issue by ericksli** [0xD34D/DesignerTools#2]
The app append the device information on the right hand side of the image but the image resolution is no change after adding the sidebar. Thus, the screenshot is transformed without maintaining correct aspect ratio. It should increase the width of the modified image.

**Comment by 0xD34D** [comment]
@ericksli What device is this on and is it possible for you to provide an example screenshot with this issue?

**Comment by ericksli** [comment]
I am using OnePlus 3T (A3003). I found that the modified screenshot file is correct in aspect ratio but the system gallery app cached the original screenshot image and thus the gallery app cannot display it with correct aspect ratio.
