### ISSUE TITLE
App won't accept permissions

### ISSUE THREAD

**Issue by dmfrey** [0xD34D/DesignerTools#3]
Just installed from Google Play Store.  It keeps taking me to the page to accept the permissions, which are accepted. But every time I try to turn on the overlay, it just takes me to the permissions page.

Google Pixel with Android 7.1.2.

Let me know what further details I can provide.

**Comment by mennovogel** [comment]
I have the same issue, also on a Google Pixel with Android 7.1.2.

**Comment by 0xD34D** [comment]
I realize this is an old issue that was not addressed further.  Please feel free to re-open if this is still an issue with Release-2.2.0
